// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnw8Gzfl_8kjJTAbZJvehC8SdVkksx4XY',
    appId: '1:644273516669:web:1235d80571092ce6ee8114',
    messagingSenderId: '644273516669',
    projectId: 'expense-9bfdc',
    authDomain: 'expense-9bfdc.firebaseapp.com',
    storageBucket: 'expense-9bfdc.appspot.com',
    measurementId: 'G-VHTHRZFY6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzY2o5pd17NPsz4k1pPLAtHAVRUnDJYws',
    appId: '1:644273516669:android:a2da548798db7532ee8114',
    messagingSenderId: '644273516669',
    projectId: 'expense-9bfdc',
    storageBucket: 'expense-9bfdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6tiYO-ZQCdxTKbJy5NenNsb-To5V4RjQ',
    appId: '1:644273516669:ios:e4c48cd1f95765c4ee8114',
    messagingSenderId: '644273516669',
    projectId: 'expense-9bfdc',
    storageBucket: 'expense-9bfdc.appspot.com',
    iosBundleId: 'com.example.myExpenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6tiYO-ZQCdxTKbJy5NenNsb-To5V4RjQ',
    appId: '1:644273516669:ios:e4c48cd1f95765c4ee8114',
    messagingSenderId: '644273516669',
    projectId: 'expense-9bfdc',
    storageBucket: 'expense-9bfdc.appspot.com',
    iosBundleId: 'com.example.myExpenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnw8Gzfl_8kjJTAbZJvehC8SdVkksx4XY',
    appId: '1:644273516669:web:0cbb5173db6e1ba9ee8114',
    messagingSenderId: '644273516669',
    projectId: 'expense-9bfdc',
    authDomain: 'expense-9bfdc.firebaseapp.com',
    storageBucket: 'expense-9bfdc.appspot.com',
    measurementId: 'G-S57L413LXJ',
  );
}
